//auth module
export const SET_APIGCLIENT_ACTION = 'SET_APIGCLIENT_ACTION';
export const SET_USER_ACTION = 'SET_USER_ACTION';
export const SET_SUCCESS_MSG_ACTION = 'SET_SUCCESS_MSG_ACTION';
export const SET_ERROR_MSG_ACTION = 'SET_ERROR_MSG_ACTION';
export const SET_ISLOGGEDIN_ACTION = 'SET_ISLOGGEDIN_ACTION';
export const SET_JWTTOKEN_ACTION = 'SET_JWTTOKEN_ACTION';

//admin, tutor, student module
export const SET_LECTURE_ACTION = 'SET_LECTURE_ACTION';
export const CLEAR_LECTURE_ACTION = 'CLEAR_LECTURE_ACTION';




